FROM training/ansible:ubuntu

RUN apt-get -y install tree
COPY hostfile /etc/ansible/hosts
COPY ansible.cfg /etc/ansible/ansible.cfg
COPY cserver.pub /root/.ssh/id_rsa.pub
COPY cserver /root/.ssh/id_rsa

RUN chmod 600 /root/.ssh/id_rsa
